Err hrWinScreenMode(WinScreenModeOperation op, UInt32 *width, UInt32 *height, UInt32 *depth, Boolean *enableColor);
void hrWinEraseRectangle(RectangleType *r, UInt16 cornerDiam);
void hrWinSetClip(RectangleType *r);
void hrWinPaintChars(const Char *chars, Int16 len, Coord x, Coord y);
void hrWinDrawChars(const Char *chars, Int16 len, Coord x, Coord y);
void hrWinFillRectangle(RectangleType *r, UInt16 cornerDiam);
void hrWinInvertRectangle(RectangleType *r, UInt16 cornerDiam);
void hrWinPaintLine(Coord x1, Coord y1, Coord x2, Coord y2);
void hrWinPaintPixel(Coord x, Coord y);
UInt32 hrWinGetPixel(Coord x, Coord y);
void hrWinPaintRectangleFrame(FrameType frame, RectangleType *r);
void hrWinPaintBitmap(BitmapType *bitmap, Coord x, Coord y);
void hrWinDrawRectangleFrame(FrameType frame, RectangleType *r);
void hrWinEraseRectangleFrame(FrameType frame, RectangleType *r);
void hrWinDrawLine(Coord x1, Coord y1, Coord x2, Coord y2);
void hrWinEraseLine(Coord x1, Coord y1, Coord x2, Coord y2);
void hrFldGetBounds(FieldType *fld, RectangleType *r);
void hrFrmGetObjectBounds(FormType *frm, UInt16 objIndex, RectangleType *r);
ControlType *hrCtlNewControl(void **form, UInt16 ID, ControlStyleType style, const Char *text, Coord x, Coord y, Coord width, Coord height, UInt16 font, UInt8 group, Boolean leftAnchor);
GraphicControlType *hrCtlNewGraphicControl(void **form, UInt16 ID, ControlStyleType style, DmResID bitmapID, DmResID selectedBitmapID, Coord x, Coord y, Coord width, Coord height, UInt8 group, Boolean leftAnchor);
SliderControlType *hrCtlNewSliderControl(void **formPP, UInt16 ID, ControlStyleType style, DmResID thumbID, DmResID backgroundID, Coord x, Coord y, Coord width, Coord height, UInt16 minValue, UInt16 maxValue, UInt16 pageSize, UInt16 value);
FieldType *hrFldNewField(void **form, UInt16 id, Coord x, Coord y, Coord width, Coord height, UInt16 font, UInt32 maxChars, Boolean editable, Boolean underlined, Boolean singleLine, Boolean dynamicSize,JustificationType justification, Boolean autoShift, Boolean hasScrollBar, Boolean numeric);
void hrRctSetRectangle(RectangleType *r, Coord left, Coord top, Coord width, Coord height);
Err hrLstNewList(void **form, UInt16 id, Coord x, Coord y, Coord width, Coord height, UInt16 font, Int16 visibleItems, Int16 triggerId);
FormLabelType *hrFrmNewLabel(FormType **form, UInt16 id, const char *text, Coord x, Coord y, FontID font);
Int16 hrFntCharHeight(void);
Int16 hrFntCharWidth(char c);
Int16 hrFntAverageCharWidth(void);
Int16 hrFntCharsWidth(char *s, Int16 len);
void hrBmpGlueGetDimensions(const BitmapType *bmp, Coord *width, Coord *height, UInt16 *rowBytes);
UInt32 RGBToLong(RGBColorType *rgb);
void LongToRGB(UInt32 c, RGBColorType *rgb);
void setforecolor(UInt32 c);
void settextcolor(UInt32 c);
void setbackcolor(UInt32 c);
void setcolors(void);
Boolean validwindow(void);
